### ISSUE TITLE
The Uptime monitoring tutorial's frontend is not working

### ISSUE THREAD

**Issue by preslavmihaylov** [encoredev/examples#101]
This tutorial:
https://encore.dev/docs/tutorials/uptime

isn't fully finished as the frontend is not working when following the instructions.

The issues are that there is a missing `monitor/status.go` file, not explained in the tutorial. Also, missing instructions on how to then regenerate the frontend client to use your backend.

The generated file, which is given out of the box, won't work for your deployment because it points to a different app, which is not currently deployed, ie it's hardcoded `https://${name}-uptime-7chi.encore.app`

**Comment by Karljoy973** [comment]
do you use a windows device or a linux device ? The exmaples seems to work on linux but not on windows

**Comment by preslavmihaylov** [comment]
I use mac. Also, bear in mind this issue was submitted in April, the tutorial might have been fixed since then.

**Comment by marcuskohlberg** [comment]
This has been fixed a while back, thanks for reporting!
